<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:macro name="omni_wheel" params="name parent angle_deg yaw">
        <xacro:property name="angle_rad" value="${float(angle_deg) * pi / 180}"/>
        <xacro:property name="x" value="${float(wheel_offset_radius) * cos(angle_rad)}"/>
        <xacro:property name="y" value="${float(wheel_offset_radius) * sin(angle_rad)}"/>

        <link name="${name}">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
                </geometry>
                <material name="black"/>
            </visual>

            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
                </geometry>
            </collision>

            <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_cylinder>

        </link>

        <joint name="${name}_joint" type="continuous">
            <parent link="${parent}"/>
            <child link="${name}"/>
            <origin xyz="${x} ${y} ${wheel_offset_z}" rpy="${-pi / 2} 0 ${yaw}"/>
            <axis xyz="0 0 1"/>
        </joint>
        
        <gazebo reference="${name}">
            <material>Gazebo/Black</material>
        </gazebo> 
    </xacro:macro>

</robot>