<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>
    <xacro:include filename="omniwheel_macros.xacro"/>

    <!-- Robot dimensions -->
    <xacro:property name="chassis_diameter" value="0.315"/>
    <xacro:property name="chassis_height" value="0.25"/>
    <xacro:property name="chassis_mass" value="1.0"/>

    <!-- Omni wheel specs -->
    <xacro:property name="wheel_radius" value="0.05"/> <!-- 10 cm diameter -->
    <xacro:property name="wheel_thickness" value="0.04"/>
    <xacro:property name="wheel_mass" value="0.05"/>
    <!-- Wheels placed at radius from center equal to chassis radius -->
    <xacro:property name="wheel_offset_radius" value="${(chassis_diameter / 2)-0.0075}"/>
    <xacro:property name="wheel_offset_z" value="0.05"/>

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <!-- BASE LINK -->

    <link name="base_link">

    </link>

    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>

    <!-- CHASSIS LINK -->
    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="0 0 ${wheel_radius+0.01}"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="0 0 ${chassis_height/2}"/>
            <geometry>
                <cylinder radius="${chassis_diameter / 2}" length="${chassis_height}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${chassis_height/2}"/>
            <geometry>
                <cylinder radius="${chassis_diameter / 2}" length="${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${chassis_mass}" length="${chassis_height}" radius="${chassis_diameter / 2}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Orange</material>
    </gazebo>  

    <!-- Wheels-->
    <xacro:omni_wheel name="wheel_1" parent="base_link" angle_deg="60" yaw="${pi-pi/6}"/>
    <xacro:omni_wheel name="wheel_2" parent="base_link" angle_deg="180" yaw="${-pi/2}"/>
    <xacro:omni_wheel name="wheel_3" parent="base_link" angle_deg="300" yaw="${pi/6}"/>
    
</robot>