ekf_filter_node:
  ros__parameters:
    frequency: 10.0  # Hz rate at which the EKF outputs fused data
    two_d_mode: true  # True if working in planar 2D environment

    # Set the frame IDs explicitly
    odom_frame: odom          # Usually "odom"
    base_link_frame: nunbot/base_footprint  # Change from base_link to base_footprint
    world_frame: odom
    imu0_frame: nunbot/imu_link  # Replace with the exact frame ID used by your IMU messages
    odom0_frame: nunbot/odom            # Replace with the frame ID used by your odometry messages


    publish_tf: true  # publish odom->nunbot/base_footprint transform

    odom0: /nunbot/odom  # Topic for odometry message
    odom0_config: [true,  true,  false,
                   false, false, true,
                   false, false, false,
                   false, false, false,
                   false, false, true]

    imu0: /bno055/imu  # Topic for IMU data
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  true,  true,  true,
                  false, false, false]
